name: ghbot
version: 1.0.0
description: GitHub Plugin for PolymorphicBot
dependencies:
  github:
    git: git://github.com/DirectMyFile/github.dart.git
  http: '>=0.11.1+1 <0.12.0'
  irc: '>=1.4.5 <1.4.9'
  polymorphic_bot:
    git: git://github.com/PolymorphicBot/PolymorphicBot.git
plugin:
  dependencies:
  - google
  commands:
    "gh-stars":
      description: "Gets the Amount of Stars a repository has"
      usage: "gh-stars [user] <repository>"