name: github
version: 1.0.0
description: GitHub Plugin for PolymorphicBot
requires:
  - "google"
dependencies:
  http: '>=0.11.1+1 <0.12.0'
  plugins: any
  irc: '>=1.4.2 <1.4.5'
  polymorphic_bot:
    git: "git://github.com/PolymorphicBot/PolymorphicBot.git"