name: ghbot
version: 1.0.0
description: GitHub Plugin for PolymorphicBot
dependencies:
  github: '>=1.0.1 <1.5.0'
  http: '>=0.11.1+1 <0.12.0'
  irc: '>=1.4.5 <1.4.9'
  polymorphic_bot:
    git: git://github.com/PolymorphicBot/PolymorphicBot.git
    version: 1.2.0
plugin:
  dependencies:
  - google
